version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "quarterly"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "quarterly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "quarterly"

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "quarterly"

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "quarterly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"

ignore:
  - dependency-type: "all"
    update-types: ["version-update:semver-major"]

open-pull-requests-limit: 3
