version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "semiannually"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
