/// Usage:
///
/// For enums:
///
/// #[ai_enum]
/// pub enum MyEnum {
///     Variant1 = 1,
///     Variant2 = 2,
/// }
///
/// For structs with enum fields:
///     
/// #[derive(AiEnumFields)]
/// pub struct MyStruct {
///     #[ai_enum_field(MyEnum)]
///     my_enum_field: AiPoint,
///     _ordinary_point: AiPoint,
/// }
///
/// This macro provides:
/// - Common enum attributes
/// - `AiEnum` implementation for converting from integer values
/// - Getter methods for enum fields in structs
/// - Validation of enum fields in structs
/// - `collect_enum_errors` method for structs to gather validation errors from enum fields'
use proc_macro::TokenStream;
use quote::quote;
use syn::{
    Attribute, Data, DeriveInput, Error, Fields, Ident, Item, ItemEnum, Path, Result,
    parse_macro_input, parse_quote,
};

/// Adds the standard derives, representation, and `AiEnum` implementation to an enum.
///
/// The call site must make `AiEnum` available in scope. The enum must not already declare
/// `derive`, `repr`, or `cfg_attr` attributes generated by this macro.
#[proc_macro_attribute]
pub fn ai_enum(attributes: TokenStream, item: TokenStream) -> TokenStream {
    if !attributes.is_empty() {
        return Error::new(
            proc_macro2::Span::call_site(),
            "#[ai_enum] does not accept arguments",
        )
        .into_compile_error()
        .into();
    }

    let item = parse_macro_input!(item as Item);

    match expand_ai_enum(item) {
        Ok(expanded) => expanded.into(),
        Err(error) => error.into_compile_error().into(),
    }
}

fn expand_ai_enum(item: Item) -> Result<proc_macro2::TokenStream> {
    let mut enum_item = match item {
        Item::Enum(item) => item,
        other => {
            return Err(Error::new_spanned(
                other,
                "#[ai_enum] can only be applied to enums",
            ));
        }
    };

    reject_generated_attributes(&enum_item)?;

    let enum_name = &enum_item.ident;
    let generated_attributes: Vec<Attribute> = vec![
        parse_quote! {
            #[derive(
                Debug,
                serde::Serialize,
                serde::Deserialize,
                Copy,
                Clone,
                PartialEq,
                strum::Display,
                PartialOrd,
                strum::FromRepr,
            )]
        },
        parse_quote! { #[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))] },
        parse_quote! { #[repr(i64)] },
    ];
    enum_item.attrs.splice(0..0, generated_attributes);

    Ok(quote! {
        #enum_item

        impl AiEnum for #enum_name {
            fn from_int(value: i64) -> Option<Self> {
                Self::from_repr(value)
            }
        }
    })
}

fn reject_generated_attributes(enum_item: &ItemEnum) -> Result<()> {
    for attribute in &enum_item.attrs {
        if attribute.path().is_ident("derive")
            || attribute.path().is_ident("repr")
            || attribute.path().is_ident("cfg_attr")
        {
            return Err(Error::new_spanned(
                attribute,
                "#[ai_enum] adds derive, repr, and cfg_attr attributes; remove this attribute",
            ));
        }
    }

    Ok(())
}

/// Generates enum-backed `AiPoint` getters and aggregate enum validation.
///
/// Mark fields with `#[ai_enum_field(EnumType)]`. Getter names always use the
/// `<field_name>_value` convention. The call site must make `AiEnum` and `ValidationErrors`
/// available in scope, and annotated fields must provide `value()`.
#[proc_macro_derive(AiEnumFields, attributes(ai_enum_field))]
pub fn derive_ai_enum_fields(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    match expand_ai_enum_fields(input) {
        Ok(expanded) => expanded.into(),
        Err(error) => error.into_compile_error().into(),
    }
}

fn expand_ai_enum_fields(input: DeriveInput) -> Result<proc_macro2::TokenStream> {
    let struct_name = input.ident;
    let struct_fields = match input.data {
        Data::Struct(data) => match data.fields {
            Fields::Named(fields) => fields.named,
            _ => {
                return Err(Error::new_spanned(
                    struct_name,
                    "AiEnumFields can only be derived for structs with named fields",
                ));
            }
        },
        _ => {
            return Err(Error::new_spanned(
                struct_name,
                "AiEnumFields can only be derived for structs",
            ));
        }
    };

    let enum_fields = struct_fields
        .iter()
        .filter_map(parse_enum_field)
        .collect::<Result<Vec<_>>>()?;

    let mut getter_names = std::collections::HashSet::new();
    for enum_field in &enum_fields {
        if !getter_names.insert(enum_field.getter.to_string()) {
            return Err(Error::new_spanned(
                &enum_field.getter,
                "AiEnumFields generated duplicate getter names",
            ));
        }
    }

    let enum_getters = enum_fields.iter().map(|enum_field| {
        let field = &enum_field.field;
        let enum_type = &enum_field.enum_type;
        let getter = &enum_field.getter;

        quote! {
            pub fn #getter(&self) -> #enum_type {
                <#enum_type as AiEnum>::from_value(self.#field.value())
            }
        }
    });

    let validations = enum_fields.iter().map(|enum_field| {
        let field = &enum_field.field;
        let enum_type = &enum_field.enum_type;

        quote! {
            errors.extend(<#enum_type as AiEnum>::from_value_errors(self.#field.value()));
        }
    });

    Ok(quote! {
        impl #struct_name {
            #(#enum_getters)*

            pub fn collect_enum_errors(&self) -> ValidationErrors {
                let mut errors = ValidationErrors::new();
                #(#validations)*
                errors
            }
        }
    })
}

struct EnumField {
    field: Ident,
    enum_type: Path,
    getter: Ident,
}

fn parse_enum_field(field: &syn::Field) -> Option<Result<EnumField>> {
    let attribute = field
        .attrs
        .iter()
        .find(|attribute| attribute.path().is_ident("ai_enum_field"))?;

    Some((|| {
        let field_name = field.ident.clone().ok_or_else(|| {
            Error::new_spanned(field, "#[ai_enum_field] requires a named struct field")
        })?;
        let enum_type = attribute.parse_args::<Path>().map_err(|_| {
            Error::new_spanned(attribute, "#[ai_enum_field] requires exactly one enum type")
        })?;
        let getter = Ident::new(&format!("{field_name}_value"), field_name.span());

        Ok(EnumField {
            field: field_name,
            enum_type,
            getter,
        })
    })())
}
