/// Build script for the `common` crate.
///
/// Reads `profile.json` and generates four typed index-enum files — one per DNP3 point type
/// (AI, BI, AO, BO) — into `OUT_DIR`. Each enum uses `#[repr(u16)]` so a variant's discriminant
/// equals its raw DNP3 index; `uid as u16` retrieves the index with no runtime lookup.
///
/// A `From<XxxUid> for UID` impl is also emitted so helpers can populate `SunSpecComment.uid`.
use std::{fmt::Write as FmtWrite, fs, path::PathBuf};

use serde_json::Value;

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let profile_path = manifest_dir.join("../../../data/profiles/full.json");
    println!("cargo:rerun-if-changed={}", profile_path.display());

    let profile_text = fs::read_to_string(&profile_path).unwrap_or_else(|err| {
        panic!(
            "Failed to read profile.json at {}: {err}",
            profile_path.display()
        )
    });
    let profile: Value = serde_json::from_str(&profile_text)
        .unwrap_or_else(|err| panic!("Failed to parse profile.json: {err}"));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));

    for (collection_key, enum_name) in [
        ("AI", "AiUid"),
        ("BI", "BiUid"),
        ("AO", "AoUid"),
        ("BO", "BoUid"),
    ] {
        let points = profile[collection_key]["points"]
            .as_array()
            .unwrap_or_else(|| panic!("Expected {collection_key}.points to be an array"));

        let content = generate_typed_uid_enum(enum_name, points);
        let out_path = out_dir.join(format!("{}.rs", enum_name.to_lowercase()));
        fs::write(&out_path, &content)
            .unwrap_or_else(|err| panic!("Failed to write {}: {err}", out_path.display()));
    }
}

/// Generate a `#[repr(u16)]` enum file for one point type.
///
/// Reads `point_index` (integer) and `iec_61850_uid` + `purpose` from each point in `full.json`.
fn generate_typed_uid_enum(enum_name: &str, points: &[Value]) -> String {
    let mut out = String::new();

    writeln!(
        out,
        "/// Generated by build.rs — do not edit directly. Re-runs when full.json changes."
    )
    .unwrap();
    writeln!(out, "#[repr(u16)]").unwrap();
    writeln!(out, "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]").unwrap();
    writeln!(out, "#[allow(non_camel_case_types)]").unwrap();
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "pub enum {enum_name} {{").unwrap();

    let mut seen_variants: std::collections::HashSet<String> = std::collections::HashSet::new();

    for point in points {
        let point_index = point["point_index"]
            .as_u64()
            .unwrap_or_else(|| panic!("Missing/invalid point_index in point: {point}"));
        let uid_str = point["iec_61850_uid"]
            .as_str()
            .unwrap_or_else(|| panic!("Missing iec_61850_uid in point: {point}"));
        let purpose = point["purpose"].as_str().unwrap_or("");
        let name = point["name"].as_str().unwrap_or("");
        let safe_name = sanitize_doc_comment(name);

        let variant = uid_to_enum_variant(uid_str, purpose);

        if seen_variants.contains(&variant) {
            continue; // Skip duplicate variant names — keep the first (lowest index) occurrence
        }
        seen_variants.insert(variant.clone());

        for line in safe_name.lines() {
            writeln!(out, "    /// {}", line.trim_start()).unwrap();
        }
        writeln!(out, "    {variant} = {point_index},").unwrap();
    }

    writeln!(out, "}}").unwrap();

    out
}

/// Replace characters that would break Rust doc comments or tokens.
fn sanitize_doc_comment(s: &str) -> String {
    s.chars()
        .map(|ch| match ch {
            '\u{2013}' | '\u{2014}' => '-',
            '\u{2018}' | '\u{2019}' => '\'',
            '\u{201c}' | '\u{201d}' => '"',
            '<' | '>' => ' ',
            ch if ch.is_ascii() => ch,
            _ => ' ',
        })
        .collect()
}

/// `"{purpose}_{uid}"` with special chars → `_`.
fn uid_to_enum_variant(uid: &str, purpose: &str) -> String {
    let combined = if purpose.is_empty() {
        uid.to_string()
    } else {
        format!("{purpose}_{uid}")
    };

    // Remove closing brackets, then replace runs of non-alphanumeric chars with `_`
    let cleaned = combined.replace(']', "");
    let mut variant = String::new();
    let mut last_was_sep = false;

    for ch in cleaned.chars() {
        if ch.is_alphanumeric() {
            variant.push(ch);
            last_was_sep = false;
        } else if !last_was_sep {
            variant.push('_');
            last_was_sep = true;
        }
    }

    // Trim trailing underscores
    let variant = variant.trim_end_matches('_').to_string();
    // Trim leading underscores (shouldn't happen but be safe)
    variant.trim_start_matches('_').to_string()
}
