use crate::profile::AiPoint;
use serde::{Deserialize, Serialize};

/// AI points belonging to the Battery equipment group.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
pub struct AiBattery {
    pub type_of_storage: AiPoint,
    pub nameplate_actual_capacity: AiPoint,
    pub effective_capacity: AiPoint,
    pub minimum_reserve: AiPoint,
    pub maximum_reserve: AiPoint,
    pub battery_state: AiPoint,
    pub actual_state_of_charge: AiPoint,
    pub state_of_health: AiPoint,
    pub external_voltage: AiPoint,
    pub internal_voltage: AiPoint,
    pub current: AiPoint,
    pub power: AiPoint,
    pub min_cell_voltage: AiPoint,
    pub max_cell_voltage: AiPoint,
    pub min_temperature: AiPoint,
    pub max_temperature: AiPoint,
    pub external_ambient_temperature: AiPoint,
    pub internal_ambient_temperature: AiPoint,
    pub charge_current_limit: AiPoint,
    pub discharge_current_limit: AiPoint,
    pub min_voltage_limit: AiPoint,
    pub max_voltage_limit: AiPoint,
    pub connected_string_count: AiPoint,
    pub external_voltage_high_threshold: AiPoint,
    pub external_voltage_low_threshold: AiPoint,
    pub internal_voltage_high_threshold: AiPoint,
    pub internal_voltage_low_threshold: AiPoint,
    pub link_to_inverter: AiPoint,
}

impl AiBattery {
    pub fn iter_points(&self) -> Vec<&AiPoint> {
        vec![
            &self.type_of_storage,
            &self.nameplate_actual_capacity,
            &self.effective_capacity,
            &self.minimum_reserve,
            &self.maximum_reserve,
            &self.battery_state,
            &self.actual_state_of_charge,
            &self.state_of_health,
            &self.external_voltage,
            &self.internal_voltage,
            &self.current,
            &self.power,
            &self.min_cell_voltage,
            &self.max_cell_voltage,
            &self.min_temperature,
            &self.max_temperature,
            &self.external_ambient_temperature,
            &self.internal_ambient_temperature,
            &self.charge_current_limit,
            &self.discharge_current_limit,
            &self.min_voltage_limit,
            &self.max_voltage_limit,
            &self.connected_string_count,
            &self.external_voltage_high_threshold,
            &self.external_voltage_low_threshold,
            &self.internal_voltage_high_threshold,
            &self.internal_voltage_low_threshold,
            &self.link_to_inverter,
        ]
    }

    pub fn iter_points_mut(&mut self) -> Vec<&mut AiPoint> {
        let Self {
            type_of_storage,
            nameplate_actual_capacity,
            effective_capacity,
            minimum_reserve,
            maximum_reserve,
            battery_state,
            actual_state_of_charge,
            state_of_health,
            external_voltage,
            internal_voltage,
            current,
            power,
            min_cell_voltage,
            max_cell_voltage,
            min_temperature,
            max_temperature,
            external_ambient_temperature,
            internal_ambient_temperature,
            charge_current_limit,
            discharge_current_limit,
            min_voltage_limit,
            max_voltage_limit,
            connected_string_count,
            external_voltage_high_threshold,
            external_voltage_low_threshold,
            internal_voltage_high_threshold,
            internal_voltage_low_threshold,
            link_to_inverter,
        } = self;

        vec![
            type_of_storage,
            nameplate_actual_capacity,
            effective_capacity,
            minimum_reserve,
            maximum_reserve,
            battery_state,
            actual_state_of_charge,
            state_of_health,
            external_voltage,
            internal_voltage,
            current,
            power,
            min_cell_voltage,
            max_cell_voltage,
            min_temperature,
            max_temperature,
            external_ambient_temperature,
            internal_ambient_temperature,
            charge_current_limit,
            discharge_current_limit,
            min_voltage_limit,
            max_voltage_limit,
            connected_string_count,
            external_voltage_high_threshold,
            external_voltage_low_threshold,
            internal_voltage_high_threshold,
            internal_voltage_low_threshold,
            link_to_inverter,
        ]
    }
}
