use serde::{Deserialize, Serialize};

use crate::profile::AiPoint;

/// AI points belonging to the Inverter equipment group.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
pub struct AiInverter {
    pub apparent_power_calc_method: AiPoint,
    pub active_power_target: AiPoint,
    pub reactive_power_target: AiPoint,
    pub active_power: AiPoint,
    pub reactive_power: AiPoint,
    pub power_factor: AiPoint,
    pub apparent_power: AiPoint,
    pub dc_input_power: AiPoint,
    pub dc_voltage: AiPoint,
    pub dc_current: AiPoint,
    pub avg_line_to_neutral_voltage: AiPoint,
    pub voltage_phase_a_to_b: AiPoint,
    pub voltage_phase_b_to_c: AiPoint,
    pub voltage_phase_c_to_a: AiPoint,
    pub ac_current: AiPoint,
    pub current_phase_a: AiPoint,
    pub current_phase_b: AiPoint,
    pub current_phase_c: AiPoint,
    pub internal_temperature: AiPoint,
    pub heat_sink_temperature: AiPoint,
    pub transformer_temperature: AiPoint,
    pub active_power_high_threshold: AiPoint,
    pub active_power_low_threshold: AiPoint,
    pub reactive_power_high_threshold: AiPoint,
    pub reactive_power_low_threshold: AiPoint,
    pub frequency_high_threshold: AiPoint,
    pub frequency_low_threshold: AiPoint,
    pub dc_input_power_high_threshold: AiPoint,
    pub dc_input_power_low_threshold: AiPoint,
    pub dc_current_high_threshold: AiPoint,
    pub dc_current_low_threshold: AiPoint,
    pub dc_voltage_high_threshold: AiPoint,
    pub dc_voltage_low_threshold: AiPoint,
    pub link_to_der_unit: AiPoint,
}

impl AiInverter {
    pub fn iter_points(&self) -> Vec<&AiPoint> {
        vec![
            &self.apparent_power_calc_method,
            &self.active_power_target,
            &self.reactive_power_target,
            &self.active_power,
            &self.reactive_power,
            &self.power_factor,
            &self.apparent_power,
            &self.dc_input_power,
            &self.dc_voltage,
            &self.dc_current,
            &self.avg_line_to_neutral_voltage,
            &self.voltage_phase_a_to_b,
            &self.voltage_phase_b_to_c,
            &self.voltage_phase_c_to_a,
            &self.ac_current,
            &self.current_phase_a,
            &self.current_phase_b,
            &self.current_phase_c,
            &self.internal_temperature,
            &self.heat_sink_temperature,
            &self.transformer_temperature,
            &self.active_power_high_threshold,
            &self.active_power_low_threshold,
            &self.reactive_power_high_threshold,
            &self.reactive_power_low_threshold,
            &self.frequency_high_threshold,
            &self.frequency_low_threshold,
            &self.dc_input_power_high_threshold,
            &self.dc_input_power_low_threshold,
            &self.dc_current_high_threshold,
            &self.dc_current_low_threshold,
            &self.dc_voltage_high_threshold,
            &self.dc_voltage_low_threshold,
            &self.link_to_der_unit,
        ]
    }

    pub fn iter_points_mut(&mut self) -> Vec<&mut AiPoint> {
        let Self {
            apparent_power_calc_method,
            active_power_target,
            reactive_power_target,
            active_power,
            reactive_power,
            power_factor,
            apparent_power,
            dc_input_power,
            dc_voltage,
            dc_current,
            avg_line_to_neutral_voltage,
            voltage_phase_a_to_b,
            voltage_phase_b_to_c,
            voltage_phase_c_to_a,
            ac_current,
            current_phase_a,
            current_phase_b,
            current_phase_c,
            internal_temperature,
            heat_sink_temperature,
            transformer_temperature,
            active_power_high_threshold,
            active_power_low_threshold,
            reactive_power_high_threshold,
            reactive_power_low_threshold,
            frequency_high_threshold,
            frequency_low_threshold,
            dc_input_power_high_threshold,
            dc_input_power_low_threshold,
            dc_current_high_threshold,
            dc_current_low_threshold,
            dc_voltage_high_threshold,
            dc_voltage_low_threshold,
            link_to_der_unit,
        } = self;

        vec![
            apparent_power_calc_method,
            active_power_target,
            reactive_power_target,
            active_power,
            reactive_power,
            power_factor,
            apparent_power,
            dc_input_power,
            dc_voltage,
            dc_current,
            avg_line_to_neutral_voltage,
            voltage_phase_a_to_b,
            voltage_phase_b_to_c,
            voltage_phase_c_to_a,
            ac_current,
            current_phase_a,
            current_phase_b,
            current_phase_c,
            internal_temperature,
            heat_sink_temperature,
            transformer_temperature,
            active_power_high_threshold,
            active_power_low_threshold,
            reactive_power_high_threshold,
            reactive_power_low_threshold,
            frequency_high_threshold,
            frequency_low_threshold,
            dc_input_power_high_threshold,
            dc_input_power_low_threshold,
            dc_current_high_threshold,
            dc_current_low_threshold,
            dc_voltage_high_threshold,
            dc_voltage_low_threshold,
            link_to_der_unit,
        ]
    }
}
