use crate::profile::BiPoint;
use serde::{Deserialize, Serialize};

/// BI points belonging to the Battery equipment group.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
pub struct BiBattery {
    pub status_of_storage: BiPoint,
    pub communication_error: BiPoint,
    pub local_control_mode: BiPoint,
    pub dc_contactor_closed: BiPoint,
    pub is_charging: BiPoint,
    pub is_discharging: BiPoint,
    pub external_voltage_too_high: BiPoint,
    pub external_voltage_too_low: BiPoint,
    pub internal_voltage_too_high: BiPoint,
    pub internal_voltage_too_low: BiPoint,
    pub over_temperature_alarm: BiPoint,
    pub under_temperature_alarm: BiPoint,
    pub temperature_imbalance_alarm: BiPoint,
    pub over_temperature_warning: BiPoint,
    pub under_temperature_warning: BiPoint,
    pub temperature_imbalance_warning: BiPoint,
    pub over_charge_current_alarm: BiPoint,
    pub over_discharge_current_alarm: BiPoint,
    pub over_charge_current_warning: BiPoint,
    pub over_discharge_current_warning: BiPoint,
    pub voltage_imbalance_warning: BiPoint,
    pub current_imbalance_warning: BiPoint,
    pub over_voltage_alarm: BiPoint,
    pub under_voltage_alarm: BiPoint,
    pub over_voltage_warning: BiPoint,
    pub under_voltage_warning: BiPoint,
    pub over_soc_max_alarm: BiPoint,
    pub under_soc_min_alarm: BiPoint,
    pub over_soc_max_warning: BiPoint,
    pub under_soc_min_warning: BiPoint,
    pub contactor_failure: BiPoint,
    pub fan_error: BiPoint,
    pub ground_fault: BiPoint,
    pub door_open_alarm: BiPoint,
    pub configuration_error: BiPoint,
    pub configuration_warning: BiPoint,
    pub other_alarm: BiPoint,
    pub other_warning: BiPoint,
    pub fire_alarm: BiPoint,
    pub fire_supervisory_warning: BiPoint,
    pub fire_trouble_warning: BiPoint,
    pub fire_power_fault_warning: BiPoint,
    pub chiller_alarm: BiPoint,
    pub chiller_warning: BiPoint,
    pub air_handler_alarm: BiPoint,
    pub air_handler_warning: BiPoint,
    pub fluid_alarm: BiPoint,
    pub fluid_warning: BiPoint,
    pub gas_alarm: BiPoint,
    pub gas_warning: BiPoint,
    pub electrolyte_alarm: BiPoint,
    pub electrolyte_warning: BiPoint,
    pub electrical_alarm: BiPoint,
    pub electrical_warning: BiPoint,
}

impl BiBattery {
    pub fn iter_points(&self) -> Vec<&BiPoint> {
        vec![
            &self.status_of_storage,
            &self.communication_error,
            &self.local_control_mode,
            &self.dc_contactor_closed,
            &self.is_charging,
            &self.is_discharging,
            &self.external_voltage_too_high,
            &self.external_voltage_too_low,
            &self.internal_voltage_too_high,
            &self.internal_voltage_too_low,
            &self.over_temperature_alarm,
            &self.under_temperature_alarm,
            &self.temperature_imbalance_alarm,
            &self.over_temperature_warning,
            &self.under_temperature_warning,
            &self.temperature_imbalance_warning,
            &self.over_charge_current_alarm,
            &self.over_discharge_current_alarm,
            &self.over_charge_current_warning,
            &self.over_discharge_current_warning,
            &self.voltage_imbalance_warning,
            &self.current_imbalance_warning,
            &self.over_voltage_alarm,
            &self.under_voltage_alarm,
            &self.over_voltage_warning,
            &self.under_voltage_warning,
            &self.over_soc_max_alarm,
            &self.under_soc_min_alarm,
            &self.over_soc_max_warning,
            &self.under_soc_min_warning,
            &self.contactor_failure,
            &self.fan_error,
            &self.ground_fault,
            &self.door_open_alarm,
            &self.configuration_error,
            &self.configuration_warning,
            &self.other_alarm,
            &self.other_warning,
            &self.fire_alarm,
            &self.fire_supervisory_warning,
            &self.fire_trouble_warning,
            &self.fire_power_fault_warning,
            &self.chiller_alarm,
            &self.chiller_warning,
            &self.air_handler_alarm,
            &self.air_handler_warning,
            &self.fluid_alarm,
            &self.fluid_warning,
            &self.gas_alarm,
            &self.gas_warning,
            &self.electrolyte_alarm,
            &self.electrolyte_warning,
            &self.electrical_alarm,
            &self.electrical_warning,
        ]
    }
}
