use crate::profile::BiPoint;
use serde::{Deserialize, Serialize};

/// BI points belonging to the Inverter equipment group.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
pub struct BiInverter {
    pub active_power_too_high: BiPoint,
    pub active_power_too_low: BiPoint,
    pub reactive_power_too_high: BiPoint,
    pub reactive_power_too_low: BiPoint,
    pub frequency_too_high: BiPoint,
    pub frequency_too_low: BiPoint,
    pub dc_input_power_too_high: BiPoint,
    pub dc_input_power_too_low: BiPoint,
    pub dc_current_too_high: BiPoint,
    pub dc_current_too_low: BiPoint,
    pub dc_voltage_too_high: BiPoint,
    pub dc_voltage_too_low: BiPoint,
    pub power_factor_excitation: BiPoint,
    pub communication_error: BiPoint,
    pub local_control_mode: BiPoint,
    pub dc_contactor_closed: BiPoint,
    pub ground_fault_alarm: BiPoint,
    pub dc_over_voltage_alarm: BiPoint,
    pub dc_under_voltage_alarm: BiPoint,
    pub ac_disconnect_warning: BiPoint,
    pub dc_disconnect_warning: BiPoint,
    pub grid_disconnect_warning: BiPoint,
    pub cabinet_open_warning: BiPoint,
    pub manual_shutdown_warning: BiPoint,
    pub over_temperature_alarm: BiPoint,
    pub under_temperature_alarm: BiPoint,
    pub over_frequency_alarm: BiPoint,
    pub under_frequency_alarm: BiPoint,
    pub ac_over_voltage_alarm: BiPoint,
    pub ac_under_voltage_alarm: BiPoint,
    pub blown_string_fuse_alarm: BiPoint,
    pub memory_loss_alarm: BiPoint,
    pub hardware_test_failure: BiPoint,
    pub other_alarm: BiPoint,
    pub other_warning: BiPoint,
}

impl BiInverter {
    pub fn iter_points(&self) -> Vec<&BiPoint> {
        vec![
            &self.active_power_too_high,
            &self.active_power_too_low,
            &self.reactive_power_too_high,
            &self.reactive_power_too_low,
            &self.frequency_too_high,
            &self.frequency_too_low,
            &self.dc_input_power_too_high,
            &self.dc_input_power_too_low,
            &self.dc_current_too_high,
            &self.dc_current_too_low,
            &self.dc_voltage_too_high,
            &self.dc_voltage_too_low,
            &self.power_factor_excitation,
            &self.communication_error,
            &self.local_control_mode,
            &self.dc_contactor_closed,
            &self.ground_fault_alarm,
            &self.dc_over_voltage_alarm,
            &self.dc_under_voltage_alarm,
            &self.ac_disconnect_warning,
            &self.dc_disconnect_warning,
            &self.grid_disconnect_warning,
            &self.cabinet_open_warning,
            &self.manual_shutdown_warning,
            &self.over_temperature_alarm,
            &self.under_temperature_alarm,
            &self.over_frequency_alarm,
            &self.under_frequency_alarm,
            &self.ac_over_voltage_alarm,
            &self.ac_under_voltage_alarm,
            &self.blown_string_fuse_alarm,
            &self.memory_loss_alarm,
            &self.hardware_test_failure,
            &self.other_alarm,
            &self.other_warning,
        ]
    }
}
